name: Continuous Integration

on:
  push:
    branches:
    - main
    #paths:
    #  - project/**
    

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

  # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11


    # Run Test
    - name: Run Test
      run: |
        find . -name "testing.py"

 #       ./main/project/testing.sh
 #       ./2023-AMSE-cs/project/testing.sh
 #chmod u+r+x testing.sh

 

  

    
