name: Continuous Integration

on:
  push:
    branches:
    - main
    paths:
      - project/**
    

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

  # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11


    # Run Test
    - name: Run Test
      run: |
        ./main/project/testing.sh
 #       ./2023-AMSE-cs/project/testing.sh

    #- name: Checkout exercise feedback
     # uses: actions/checkout@v3
      #with:
       # repository: jvalue/amse-exercise-feedback
        #path: grading

  

    
