name: Continuous Integration

on:
  push:
    branches:
    - main
    
    

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

  # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: python -m pip install --upgrade pip pandas


    # Run Test
    - name: Run Test
      run: |
        chmod u+r+x ./main/project/testing.sh
        ./main/project/testing.sh
 

 

  

    
